/**
 * Measures how much ink each candidate glyph puts on the page, in the same
 * font stack the site renders with, and writes the result to lib/ramp.json.
 *
 * Guessing which characters look darker is what produces banding: two glyphs
 * that feel different can carry near-identical coverage, so a stretch of skin
 * flattens into one tone. Measuring removes the guess.
 *
 *   node scripts/calibrate-ramp.mjs
 */
import { chromium } from "playwright-core";
import { writeFile } from "node:fs/promises";

// Anything that reads as a shade rather than as punctuation with meaning.
const CANDIDATES = [
  " ", "`", ".", "'", ",", ":", ";", "-", "~", "!", "^", "\"", "_",
  "*", "+", "=", "<", ">", "i", "l", "r", "c", "v", "?", "t", "f",
  "j", "z", "x", "n", "u", "o", "w", "a", "h", "k", "b", "d", "p",
  "q", "m", "0", "O", "Z", "X", "%", "#", "8", "B", "&", "W", "M",
  "$", "@",
];

// Directional glyphs, measured too so an edge can be matched to a tone.
const EDGES = ["|", "/", "\\", "_", "-"];

const FONT =
  'ui-monospace, "SFMono-Regular", "JetBrains Mono", Menlo, Consolas, monospace';

const exe =
  process.env.HOME +
  "/Library/Caches/ms-playwright/chromium-1223/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";

const browser = await chromium.launch({ executablePath: exe });
const page = await browser.newPage();

const coverage = await page.evaluate(
  ([chars, font]) => {
    const SIZE = 64;
    const cv = document.createElement("canvas");
    const ctx = cv.getContext("2d", { willReadFrequently: true });
    ctx.font = `${SIZE}px ${font}`;
    const cellW = Math.ceil(ctx.measureText("M").width);
    const cellH = Math.ceil(SIZE * 1.3);
    cv.width = cellW;
    cv.height = cellH;

    const out = {};
    for (const ch of chars) {
      ctx.fillStyle = "#fff";
      ctx.fillRect(0, 0, cellW, cellH);
      ctx.fillStyle = "#000";
      ctx.font = `${SIZE}px ${font}`;
      ctx.textBaseline = "alphabetic";
      ctx.fillText(ch, 0, SIZE);

      const { data } = ctx.getImageData(0, 0, cellW, cellH);
      let ink = 0;
      for (let i = 0; i < data.length; i += 4) ink += 255 - data[i];
      out[ch] = ink / (cellW * cellH * 255);
    }
    return out;
  },
  [[...CANDIDATES, ...EDGES], FONT]
);

await browser.close();

const lo = coverage[" "];
const hi = Math.max(...Object.values(coverage));
const norm = (v) => (v - lo) / (hi - lo);

/**
 * Pick `n` glyphs whose measured coverage is as evenly spaced as possible.
 * An even spread is what keeps a gradient reading as a gradient.
 */
function buildRamp(n) {
  const pool = CANDIDATES.map((ch) => ({ ch, v: norm(coverage[ch]) })).sort((a, b) => a.v - b.v);
  const ramp = [];
  for (let i = 0; i < n; i++) {
    const target = i / (n - 1);
    let best = pool[0];
    for (const p of pool) {
      if (Math.abs(p.v - target) < Math.abs(best.v - target)) best = p;
    }
    if (!ramp.some((r) => r.ch === best.ch)) ramp.push(best);
  }
  return ramp;
}

const ramp = buildRamp(12);
const edges = Object.fromEntries(EDGES.map((ch) => [ch, norm(coverage[ch])]));

await writeFile(
  "lib/ramp.json",
  JSON.stringify(
    {
      note: "Generated by scripts/calibrate-ramp.mjs — measured ink coverage, not guessed.",
      font: FONT,
      // Light to dark.
      ramp: ramp.map((r) => r.ch),
      rampCoverage: ramp.map((r) => Number(r.v.toFixed(4))),
      edges,
    },
    null,
    2
  ) + "\n"
);

console.log("ramp (light → dark):", ramp.map((r) => `${JSON.stringify(r.ch)}=${r.v.toFixed(3)}`).join("  "));
console.log("edges:", Object.entries(edges).map(([c, v]) => `${c}=${v.toFixed(3)}`).join("  "));
